# Generated by Django 3.2.6 on 2021-08-10 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecast', '0003_auto_20210810_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.FileField(blank=True, null=True, upload_to='train/%Y%m%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'train',
            },
        ),
    ]
